<?php

namespace Database\Seeders;

use App\Models\EmailCargo;
use App\Models\EmailMovementType;
use App\Models\Priority;
use App\Models\SystemStatus;
use App\Models\TaskStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        foreach ([
            'pendiente',
            'en progreso',
            'completada',
            'cancelada',
            'rechazado',
        ] as $status) {
            TaskStatus::query()->updateOrCreate(
                ['slug' => Str::slug($status)],
                ['name' => $status],
            );
        }

        foreach ([
            ['name' => 'baja', 'weight' => 1],
            ['name' => 'media', 'weight' => 2],
            ['name' => 'alta', 'weight' => 3],
            ['name' => 'urgente', 'weight' => 4],
        ] as $priority) {
            Priority::query()->updateOrCreate(
                ['slug' => Str::slug($priority['name'])],
                $priority,
            );
        }

        foreach ([
            'Alta',
            'Baja',
            'Cambio de contraseña',
        ] as $movementType) {
            EmailMovementType::query()->updateOrCreate(
                ['slug' => Str::slug($movementType)],
                ['name' => $movementType],
            );
        }

        $emailCargoNames = [
            'Secretario de Movilidad',
            'Directora General de Asuntos Jurídicos',
            'Director de lo Consultivo',
            'Subdirectora de Contratos y Convenios',
            'Subdirectora de Estudios, Consultas y Apoyo a Órganos de Gobierno',
            'Jefa de Unidad Departamental de Atención a Requerimientos Judiciales',
            'Jefa de Unidad Departamental de Legislación',
            'Director de lo Contencioso',
            'Subdirector de Amparo y Penal',
            'Jefe de Unidad Departamental de Amparos',
            'Jefe de Unidad Departamental de Administración de Procedimientos Penales',
            'Jefa de Unidad Departamental de Asuntos Penales',
            'Subdirector de lo Contencioso, Laboral y Administrativo',
            'Jefe de Unidad Departamental de Procedimientos Administrativos',
            'Jefa de Unidad Departamental de Procedimientos Laborales',
            'Directora General de Administración y Finanzas',
            'Coordinador de Finanzas',
            'Subdirectora de Control Presupuestal',
            'Jefe de Unidad Departamental de Auditoría Financiera',
            'Jefe de Unidad Departamental de Tesorería',
            'Jefe de Unidad Departamental de Contabilidad y Registro',
            'Coordinadora de Administración de Capital Humano',
            'Subdirectora de Desarrollo Organizacional y Capacitación',
            'Jefa de Unidad Departamental de Control de Personal y Política Laboral',
            'Jefa de Unidad Departamental Nóminas y Prestaciones',
            'Líder Coordinador de Proyectos de Nóminas',
            'Coordinador de Recursos Materiales, Abastecimiento y Servicios',
            'Subdirector de Abastecimientos y Servicios',
            'Jefe de Unidad Departamental de Abastecimientos y Servicios',
            'Líder Coordinador de Proyectos de Apoyo a Abastecimientos y Servicios',
            'Enlace Administrativo de Servicios Generales',
            'Subdirector de Compras y Control de Materiales',
            'Jefa de Unidad Departamental de Almacenes e Inventarios',
            'Líder Coordinador de Proyectos de Apoyo de Almacenes e Inventarios',
            'Enlace Administrativo de Almacenes e Inventarios',
            'Jefe de Unidad Departamental de Control de Compras de Materiales',
            'Líder Coordinador de Proyectos de Apoyo de Control de Materiales',
            'Jefa de Unidad Departamental de Control de Archivos',
            'Subsecretario del Transporte',
            'Subdirectora de Seguimiento de Hechos de Tránsito en el Transporte Público Concesionado',
            'Director General de Registro Público de Transporte',
            'Subdirector de Archivo',
            'Jefa de Unidad Departamental de Archivo de Licencias y Control Vehicular de Transporte Público Individual de Pasajeros',
            'Jefe de Unidad Departamental de Archivo de Licencias y Control Vehicular de Transporte Público Colectivo, Mercantil y de Carga',
            'Jefa de Unidad Departamental de Archivo de Licencias y Control Vehicular Particular',
            'Subdirector Concentración y Vinculación de Bases de Datos del Registro del Transporte',
            'Jefe de Unidad Departamental de Registro de Transporte Público Individual',
            'Jefe de Unidad Departamental de Concentración de Base de Datos',
            'Jefe de Unidad Departamental de Registro de Transporte de Ruta',
            'Subdirector de Enlace con REPUVE',
            'Subdirector de Información Registral',
            'Jefe de Unidad Departamental de Información y Certificación',
            'Jefa de Unidad Departamental de Proceso Registral',
            'Subdirector de Validación y Proceso Registral',
            'Jefa de Unidad Departamental de Renovación de Equipo de Transporte',
            'Jefe de Unidad Departamental de Validación del Transporte',
            'Jefa de Unidad Departamental de Diseño y Adecuación de Normas Técnicas',
            'Director General de Licencias y Operación del Transporte Vehicular',
            'Director Operativo de Transporte Público Individual',
            'Subdirectora de Permisos y Concesiones',
            'Jefa de Unidad Departamental de Control de Sitios y Bases',
            'Jefe de Unidad Departamental de Supervisión de Licencias de Conducir',
            'Jefe de Unidad Departamental de Control Vehicular',
            'Jefe de Unidad Departamental de Análisis y Apoyo Normativo de Transporte Público Individual',
            'Jefe de Unidad Departamental de Ciclotaxis y Vehículos Adaptados de Último Tramo',
            'Subdirector de Seguimiento e Integración de Transporte Público',
            'Jefe de Unidad Departamental de Revista Vehicular y Seguimiento a la Operación',
            'Jefe de Unidad Departamental de Atención Ciudadana y Sistematización de Datos',
            'Jefa de Unidad Departamental de Proyectos Estratégicos y Mejora del Transporte Público Individual',
            'Director de Transporte de Carga y Especializado',
            'Subdirector de Transporte de Carga y Pasajeros',
            'Jefa de Unidad Departamental de Control Vehicular de Transporte de Carga y Pasajeros',
            'Jefe de Unidad Departamental de Sitios, Revista de Carga y Pasajeros',
            'Director de Transporte Particular',
            'Jefa de Unidad Departamental de Supervisión a los Centros de Servicio de Transporte Particular',
            'Jefe de Unidad Departamental de Análisis y Apoyo Normativo de Transporte Particular',
            'Subdirectora de Licencias y Permisos',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 6',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 5',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 4',
            'Jefe de Unidad Departamental de Control de Gestión de Transporte Particular',
            'Jefa de Unidad Departamental de Seguimiento a la Atención Ciudadana de Transporte Particular',
            'Subdirectora de Control Vehicular',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 1',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 2',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 3',
            'Subdirector de Soporte a la Operación de los Centros de Servicios de Control Vehicular',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 10',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 12',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 11',
            'Subdirectora de Programación, Dotación y Control de Insumos',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 7',
            'Jefe de Unidad Departamental de Enlace con Centro de Servicio 8',
            'Jefa de Unidad Departamental de Enlace con Centro de Servicio 9',
            'Director de Operación y Licencias de Transporte de Ruta y Especializado',
            'Subdirector de Control Vehicular y Licencias (Ruta)',
            'Jefa de Unidad Departamental de Expedición de Licencias de Conducir Módulo 2',
            'Jefe de Unidad Departamental de Expedición de Licencias de Conducir Módulo 1',
            'Jefe de Unidad Departamental de Revista y Control de Registro Vehicular Región Sur',
            'Jefa de Unidad Departamental de Control de Registro Vehicular Región Norte',
            'Jefa de Unidad Departamental de Depósitos Vehiculares',
            'Subdirector de Operación y Proyectos del Transporte de Ruta',
            'Jefe de Unidad Departamental de Análisis y Apoyo Normativo del Transporte de Ruta',
            'Jefa de Unidad Departamental de Capacitación y Operación del Transporte de Ruta',
            'Jefe de Unidad Departamental de Regulación de Bases y Recorridos',
            'Asesora "A" de la Secretaría de Movilidad',
            'Directora de la Unidad de Transparencia y Mejora Institucional',
            'Jefe de Unidad Departamental de Información Pública y Datos Personales',
            'Secretario Particular de la Secretaría de Movilidad',
            'Asesor "B" de la Secretaría de Movilidad',
            'Subsecretario de Planeación, Políticas y Regulación',
            'Director General de Planeación y Políticas',
            'Director de Gestión de Proyectos de la Movilidad',
            'Subdirector de Estudios de Movilidad',
            'Jefe de Unidad Departamental de Estudios de Infraestructura',
            'Jefe de Unidad Departamental de Estudios de Economía de la Movilidad',
            'Jefe de Unidad Departamental de Estudios de Movilidad Metropolitana',
            'Subdirector de Definición de Proyectos',
            'Jefe de Unidad Departamental de Requerimiento de Infraestructura Vial',
            'Jefa de Unidad Departamental de Impactos de Movilidad',
            'Jefe de Unidad Departamental de Proyectos de Ingeniería de Tránsito',
            'Jefa de Unidad Departamental de Requerimiento de Proyectos',
            'Subdirector de Análisis de Proyectos de Transporte Público',
            'Jefe de Unidad Departamental de Planeación del Transporte Público',
            'Subdirectora de Infraestructura Ciclista y Peatonal',
            'Jefe de Unidad Departamental de Planeación de Infraestructura Ciclista',
            'Jefe de Unidad Departamental de Planeación de Infraestructura Peatonal',
            'Directora de Planeación y Programación',
            'Subdirectora de Programación',
            'Jefe de Unidad Departamental de Programación',
            'Jefe de Unidad Departamental de Integración de Indicadores de Programas',
            'Jefa de Unidad Departamental de Medición y Seguimiento de Programas',
            'Director General de Seguridad Vial y Sistemas de Movilidad Urbana Sustentable',
            'Director de Seguridad Vial y Seguimiento a la Información',
            'Subdirector de Monitoreo e Información',
            'Jefe de Unidad Departamental de Seguimiento a la Seguridad Vial',
            'Subdirectora de Cultura y Uso de Bicicleta',
            'Director Ejecutivo de Regulación de Sistemas de Movilidad Urbana Sustentable',
            'Subdirectora de Estacionamiento en la Vía Pública',
            'Jefe de Unidad Departamental de Ingresos de Estacionamiento en la Vía Pública',
            'Jefa de Unidad Departamental de Planeación y Seguimiento de Proyectos e Infraestructura',
            'Jefe de Unidad Departamental de Permisionarios y Permisos para Residentes',
            'Subdirector de Sistemas Ciclistas',
            'Jefa de Unidad Departamental de Biciestacionamientos Masivos',
            'Jefa de Unidad Departamental de Supervisión del Sistema ECOBICI',
            'Jefa de Unidad Departamental de Regulación de Sistemas Ciclistas',
            'Subdirectora de Normas Técnicas',
            'Jefa de Unidad Departamental de Capacitación y Accesibilidad para la Movilidad',
            'Jefa de Unidad Departamental de Normas Técnicas para la Movilidad',
            'Subdirector de Consulta Legal de Seguridad Vial y Sistemas de Movilidad Urbana Sustentable',
            'Jefe de Unidad Departamental de Regulación de la Movilidad',
            'Jefe de Unidad Departamental de Normatividad de Seguridad Vial y Sistemas de Movilidad Urbana Sustentable',
            'Director General de Coordinación de Organismos Públicos y Proyectos Estratégicos',
            'Directora de Información y Seguimiento de la Movilidad',
            'Jefe de Unidad Departamental de Información de la Movilidad',
            'Jefe de Unidad Departamental de Seguimiento de la Movilidad',
            'Directora de Evaluación Financiera y Presupuestal de Organismos Públicos',
            'Subdirectora de Evaluación Presupuestal',
            'Jefe de Unidad Departamental de Análisis Presupuestal de los Organismos de Transporte',
            'Subdirector de Evaluación Financiera',
            'Jefe de Unidad Departamental de Análisis Financiero',
            'Directora de Coordinación Estratégica',
            'Jefa de Unidad Departamental de Seguimiento de Proyectos Estratégicos "A"',
            'Jefa de Unidad Departamental de Seguimiento de Proyectos Estratégicos "B"',
            'Director Ejecutivo de Tecnologías de Recaudo',
            'Subdirector de Diseño, Desarrollo e Innovación de Tecnologías de Recaudo',
            'Subdirectora de Seguridad y Supervisión de Sistemas de Gestión de Recaudo',
            'Coordinador General de Enlace Interinstitucional Territorial y Ciudadano',
            'Director de Coordinación Territorial',
            'Subdirectora de Seguimiento de Acuerdos',
            'Subdirector de Seguimiento Territorial',
            'Líder Coordinador de Proyectos de Apoyo Territorial',
            'Director de Enlace Interinstitucional',
            'Subdirectora de Vinculación Interinstitucional',
            'Subdirector de Concertación para la Movilidad',
            'Líder Coordinador de Proyectos de Apoyo a Concertación',
            'Directora General de Seguimiento, Proyectos y Asuntos Estratégicos de Movilidad',
            'Subdirectora de Seguimiento Institucional y de Proyectos de Movilidad',
            'Directora Técnica de Análisis de Proyectos Estratégicos de Movilidad',
            'Subdirector de Enlace Legislativo y Gestión de Proyectos Gubernamentales',
            'Director Ejecutivo de Tecnologías de la Información y Comunicación',
            'Director de Telecomunicaciones',
            'Subdirector de Infraestructura de Tecnologías de la Información',
            'Jefe de Unidad Departamental de Administración de Infraestructura de Tecnologías de la Información',
            'Subdirector de Comunicaciones y Soporte Técnico',
            'Jefe de Unidad Departamental de Redes y Seguridad',
            'Jefa de Unidad Departamental de Soporte Técnico',
            'Jefa de Unidad Departamental de Servicios al Usuario',
            'Director de Sistemas de Información',
            'Subdirector de Base de Datos y Página Web',
            'Jefa de Unidad Departamental de Página Web',
            'Jefe de Unidad Departamental de Base de Datos',
            'Subdirector de Sistemas Sustantivos y Administrativos',
            'Jefe de Unidad Departamental de Mantenimiento y Desarrollo de Sistemas Administrativos',
            'Jefe de Unidad Departamental de Mantenimiento y Desarrollo de Sistemas Sustantivos',
            'Director de Gestión de Proyectos de Innovación',
            'Jefe de Unidad Departamental de Seguimiento de Proyectos de Tecnologías de la Información',
            'Director Ejecutivo de Cultura de la Movilidad',
            'Subdirectora de Difusión e Información',
            'Jefa de Unidad Departamental de Diseño para la Difusión de la Cultura de la Movilidad',
            'Jefe de Unidad Departamental de Análisis para la Difusión de la Cultura de la Movilidad',
        ];

        $emailCargoParentIndexes = [
            null, 0, 1, 2, 2, 4, 4, 1, 7, 8, 8, 8, 7, 12, 12, 0, 15, 16, 17, 17, 17, 15, 21, 22, 22, 24,
            15, 26, 27, 28, 29, 26, 31, 32, 33, 31, 35, 26, 0, 38, 38, 40, 41, 41, 41, 40, 45, 45, 45, 40,
            40, 50, 50, 40, 53, 53, 53, 38, 57, 58, 59, 59, 59, 58, 58, 58, 65, 65, 65, 57, 69, 70, 70, 57,
            73, 73, 73, 76, 76, 76, 73, 73, 73, 82, 82, 82, 73, 86, 86, 86, 73, 90, 90, 90, 57, 94, 95, 95,
            95, 95, 94, 94, 101, 101, 101, 0, 0, 106, 0, 0, 0, 110, 111, 112, 113, 113, 113, 112, 117, 117,
            117, 117, 112, 122, 112, 124, 124, 111, 127, 128, 128, 128, 110, 132, 133, 133, 133, 132, 137,
            138, 138, 138, 137, 142, 142, 142, 137, 146, 146, 132, 149, 149, 110, 152, 153, 153, 152, 156,
            157, 156, 159, 152, 161, 161, 152, 164, 164, 0, 167, 168, 168, 170, 167, 172, 172, 174, 0, 176,
            176, 176, 176, 180, 181, 182, 181, 184, 181, 181, 180, 188, 189, 189, 188, 192, 192, 180, 195,
            176, 197, 198, 198,
        ];

        foreach ($emailCargoNames as $index => $cargo) {
            EmailCargo::query()->updateOrCreate(
                ['slug' => Str::slug($cargo)],
                [
                    'name' => $cargo,
                    'sort_order' => $index + 1,
                    'parent_name' => ($emailCargoParentIndexes[$index] ?? null) !== null
                        ? $emailCargoNames[$emailCargoParentIndexes[$index]]
                        : null,
                ],
            );
        }

        foreach ([
            'En proceso de reunion',
            'En proceso de diagramacion',
            'Proceso de validacion',
            'Visto bueno del diagrama',
            'En pruebas',
        ] as $status) {
            SystemStatus::query()->updateOrCreate(
                ['slug' => Str::slug($status)],
                ['name' => $status],
            );
        }
    }
}
